source 'https://rubygems.org'

gem 'rake'
#gem 'cocoapods'
gem 'bubble-wrap'
gem 'motion_data_wrapper'
gem 'motion-bundler'
gem 'motion-cocoapods'
gem 'motion-testflight'
#gem 'xcodeproj', '~> 0.8.1'
gem 'xcodeproj'
gem 'ib'
